### ISSUE TITLE
No pueo hacer

### ISSUE THREAD

**Issue by ReoP159** [LogicWrite/Algorithm-class-functions#4]
`
string doubleToString(double i){
	
	int entero=i;
	int digitos=digitCount(i);
	double decimales=i-entero;
	double decimalesEncontrados = 0;
	int contadorDeDecimales = 1;
	string numD = "";
	string numero="";
	
	while(decimales =! decimalesEncontrados ){
		contadorDeDecimales*=10;
		int decimalesE = (decimales - decimalesEncontrados) * (contadorDeDecimales);
		cout << entero << endl;
		numD += intToString(decimalesE);
		
		decimalesEncontrados = stringToInt(numD,10)/contadorDeDecimales;
		
		
	}
	

	
	for(int d=0;d<digitos;d++){
		char caracter=intToChar(getDigit(i,d));
		numero=caracter+numero;
	}

	return numero + numD;

} `

**Comment by LogicWrite** [comment]
`string doubleToString(double i){

	int entero=i;
	int digitos=digitCount(i);
	double decimales=i-entero;
	double decimalesN = decimales;
	double decimalesEncontrados = 0;
	int contadorDeDecimales = 1;
	string numD = "";
	string numero="";

	int d = decimales*1000000000;
	while (getDigit(d,0) == 0){
		d = d/10;
	}
	numD = intToString(d);



for(int d=0;d<digitos;d++){
	char caracter=intToChar(getDigit(i,d));
	numero=caracter+numero;
}

return numero +"."+ numD;

} `
